apiVersion: skaffold/v2beta26
kind: Config
metadata:
  name: yaara-microservices
build:
  artifacts:
    - image: web-server-1
      context: web-server-1
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "**/*.js"
            dest: /usr/src/app
          - src: "**/*.json"
            dest: /usr/src/app
    - image: web-server-2
      context: web-server-2
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "**/*.js"
            dest: /usr/src/app
          - src: "**/*.json"
            dest: /usr/src/app
deploy:
  kubectl:
    manifests:
      - web-server-1/local-deployment.yml
      - web-server-1/local-service.yml
      - web-server-2/local-deployment.yml
      - web-server-2/local-service.yml
      - local-ingress.yml
profiles:
  - name: dev
    build:
      local:
        push: false
    deploy:
      kubectl:
        manifests:
          - web-server-1/local-deployment.yml
          - web-server-1/local-service.yml
          - web-server-2/local-deployment.yml
          - web-server-2/local-service.yml
          - local-ingress.yml
