apiVersion: apps/v1
kind: Deployment
metadata:
  name: s1-deployment
  namespace: dev
  labels:
    app: web-server-1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web-server-1
  template:
    metadata:
      labels:
        app: web-server-1
    spec:
      containers:
        - name: web-server-1
          image: ayanabha1/web-server-1
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
