apiVersion: apps/v1
kind: Deployment
metadata:
  name: s2-deployment
  namespace: dev
  labels:
    app: web-server-2
spec:
  replicas: 3
  selector:
    matchLabels:
      app: web-server-2
  template:
    metadata:
      labels:
        app: web-server-2
    spec:
      containers:
        - name: web-server-2
          image: ayanabha1/web-server-2
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
