apiVersion: v1
kind: Service
metadata:
  name: server-1-service
  namespace: dev
spec:
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      nodePort: 30001
  type: NodePort
  selector:
    app: web-server-1
