apiVersion: v1
kind: Service
metadata:
  name: server-2-service
  namespace: dev
spec:
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      nodePort: 30002
  type: NodePort
  selector:
    app: web-server-2
