apiVersion: apps/v1
kind: Deployment
metadata:
  name: s2-deployment
  namespace: dev
  labels:
    app: web-server-2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-server-2
  template:
    metadata:
      labels:
        app: web-server-2
    spec:
      containers:
        - name: web-server-2
          image: web-server-2:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8000
